ci: 处理离线安装包带legacy名称问题

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,66 +29,72 @@ jobs:
       contents: write
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+      - uses: actions/checkout@v4
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v3
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    - name: package_offline
-      id: image_tag
-      run: |
-        echo arch: $(arch)
-        echo version: ${{ env.version }}
-        id
-        bash build.sh
+      - name: package_offline
+        id: image_tag
+        run: |
+          echo arch: $(arch)
+          echo version: ${{ env.version }}
+          id
+          bash build.sh
 
-    - name: Rename offline artifacts and Generate MD5 checksum
-      run: |
-        cd harbor
-        BASE="harbor-offline-installer-${{ env.version }}.tgz"
-        NEW_BASE="harbor-offline-installer-aarch64-v${{ env.version }}.tgz"
-        
-        # 重命名三个文件（若存在则移动，不存在则忽略）
-        mv -v ${BASE} ${NEW_BASE}
-        
-        ls -la
-        
-        # 生成md5
-        if [ -f "$NEW_BASE" ]; then
-          md5sum "$NEW_BASE" > "md5sum"
-          echo "$NEW_BASE md5sum: $(cat md5sum)"
-        else
-          echo "X $NEW_BASE not found!"
-          exit 1
-        fi
+      - name: Rename offline artifacts and Generate MD5 checksum
+        run: |
+          cd harbor
+          BASE="harbor-offline-installer-${{ env.version }}.tgz"
+          NEW_BASE="harbor-offline-installer-aarch64-v${{ env.version }}.tgz"
+          
+          # 文件名问题处理
+          if [ -f "harbor-offline-installer-${{ env.version }}-legacy.tgz" ]; then
+            BASE="harbor-offline-installer-${{ env.version }}-legacy.tgz"
+            echo "Found legacy installer, Rename ${BASE} To ${NEW_BASE}"
+          fi
+          
+          # 重命名三个文件（若存在则移动，不存在则忽略）
+          mv -v ${BASE} ${NEW_BASE}
+          
+          ls -la
+          
+          # 生成md5
+          if [ -f "$NEW_BASE" ]; then
+            md5sum "$NEW_BASE" > "md5sum"
+            echo "$NEW_BASE md5sum: $(cat md5sum)"
+          else
+            echo "X $NEW_BASE not found!"
+            exit 1
+          fi
 
-    - name: Build and push Docker image
-      uses: docker/build-push-action@v3
-      with:
-        context: .
-        push: true
-        build-args: version=v${{ env.version }}
-        tags: ${{ github.event.inputs.docker_project }}/${{ github.event.inputs.image_name }}:v${{ env.version }}
-        platforms: linux/amd64, linux/arm64
-        file: Dockerfile
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v3
+        with:
+          context: .
+          push: true
+          build-args: version=v${{ env.version }}
+          tags: ${{ github.event.inputs.docker_project }}/${{ github.event.inputs.image_name }}:v${{ env.version }}
+          platforms: linux/amd64, linux/arm64
+          file: Dockerfile
 
-    - name: Upload artifacts to Release
-      uses: softprops/action-gh-release@v1
-      with:
-        tag_name: v${{ env.version }}
-        name: Release v${{ env.version }}
-        draft: false
-        prerelease: false
-        files: |
-          harbor/harbor-offline-installer-aarch64-v${{ env.version }}.tgz
-          harbor/md5sum
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Upload artifacts to Release
+        uses: softprops/action-gh-release@v1
+        with:
+          tag_name: v${{ env.version }}
+          name: Release v${{ env.version }}
+          draft: false
+          prerelease: false
+          files: |
+            harbor/harbor-offline-installer-aarch64-v${{ env.version }}.tgz
+            harbor/md5sum
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
